name: flutter_firestore_todos
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  todos_repository:
    path: todos_repository
  user_repository:
    path: user_repository
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
